// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: thawr/v1/control.proto

package thawrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnrollRequest carries the token and the client's identity.
type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// token is the one-time enrollment secret (thawr_...).
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// public_key is the client's WireGuard public key, base64.
	PublicKey     string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Hostname      string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os            string `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string `protobuf:"bytes,5,opt,name=arch,proto3" json:"arch,omitempty"`
	ClientVersion string `protobuf:"bytes,6,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// name optionally requests a peer name; the token's name or the
	// hostname is used otherwise.
	Name          string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_thawr_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thawr_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_thawr_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *EnrollRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *EnrollRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *EnrollRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// EnrollResponse is returned once; node_secret is never shown again.
type EnrollResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PeerId           string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ipv4             string                 `protobuf:"bytes,3,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	OverlayCidr      string                 `protobuf:"bytes,4,opt,name=overlay_cidr,json=overlayCidr,proto3" json:"overlay_cidr,omitempty"`
	NodeSecret       string                 `protobuf:"bytes,5,opt,name=node_secret,json=nodeSecret,proto3" json:"node_secret,omitempty"`
	HubPublicKey     string                 `protobuf:"bytes,6,opt,name=hub_public_key,json=hubPublicKey,proto3" json:"hub_public_key,omitempty"`
	HubEndpoint      string                 `protobuf:"bytes,7,opt,name=hub_endpoint,json=hubEndpoint,proto3" json:"hub_endpoint,omitempty"`
	ServerVersion    string                 `protobuf:"bytes,8,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	NetmapGeneration int64                  `protobuf:"varint,9,opt,name=netmap_generation,json=netmapGeneration,proto3" json:"netmap_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_thawr_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thawr_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_thawr_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *EnrollResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnrollResponse) GetIpv4() string {
	if x != nil {
		return x.Ipv4
	}
	return ""
}

func (x *EnrollResponse) GetOverlayCidr() string {
	if x != nil {
		return x.OverlayCidr
	}
	return ""
}

func (x *EnrollResponse) GetNodeSecret() string {
	if x != nil {
		return x.NodeSecret
	}
	return ""
}

func (x *EnrollResponse) GetHubPublicKey() string {
	if x != nil {
		return x.HubPublicKey
	}
	return ""
}

func (x *EnrollResponse) GetHubEndpoint() string {
	if x != nil {
		return x.HubEndpoint
	}
	return ""
}

func (x *EnrollResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *EnrollResponse) GetNetmapGeneration() int64 {
	if x != nil {
		return x.NetmapGeneration
	}
	return 0
}

var File_thawr_v1_control_proto protoreflect.FileDescriptor

const file_thawr_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x16thawr/v1/control.proto\x12\bthawr.v1\"\xbf\x01\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x05 \x01(\tR\x04arch\x12%\n" +
	"\x0eclient_version\x18\x06 \x01(\tR\rclientVersion\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\"\xb2\x02\n" +
	"\x0eEnrollResponse\x12\x17\n" +
	"\apeer_id\x18\x01 \x01(\tR\x06peerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04ipv4\x18\x03 \x01(\tR\x04ipv4\x12!\n" +
	"\foverlay_cidr\x18\x04 \x01(\tR\voverlayCidr\x12\x1f\n" +
	"\vnode_secret\x18\x05 \x01(\tR\n" +
	"nodeSecret\x12$\n" +
	"\x0ehub_public_key\x18\x06 \x01(\tR\fhubPublicKey\x12!\n" +
	"\fhub_endpoint\x18\a \x01(\tR\vhubEndpoint\x12%\n" +
	"\x0eserver_version\x18\b \x01(\tR\rserverVersion\x12+\n" +
	"\x11netmap_generation\x18\t \x01(\x03R\x10netmapGeneration2F\n" +
	"\aControl\x12;\n" +
	"\x06Enroll\x12\x17.thawr.v1.EnrollRequest\x1a\x18.thawr.v1.EnrollResponseBDZBgithub.com/thedatadudech/thawr/internal/api/proto/thawr/v1;thawrv1b\x06proto3"

var (
	file_thawr_v1_control_proto_rawDescOnce sync.Once
	file_thawr_v1_control_proto_rawDescData []byte
)

func file_thawr_v1_control_proto_rawDescGZIP() []byte {
	file_thawr_v1_control_proto_rawDescOnce.Do(func() {
		file_thawr_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thawr_v1_control_proto_rawDesc), len(file_thawr_v1_control_proto_rawDesc)))
	})
	return file_thawr_v1_control_proto_rawDescData
}

var file_thawr_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thawr_v1_control_proto_goTypes = []any{
	(*EnrollRequest)(nil),  // 0: thawr.v1.EnrollRequest
	(*EnrollResponse)(nil), // 1: thawr.v1.EnrollResponse
}
var file_thawr_v1_control_proto_depIdxs = []int32{
	0, // 0: thawr.v1.Control.Enroll:input_type -> thawr.v1.EnrollRequest
	1, // 1: thawr.v1.Control.Enroll:output_type -> thawr.v1.EnrollResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thawr_v1_control_proto_init() }
func file_thawr_v1_control_proto_init() {
	if File_thawr_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thawr_v1_control_proto_rawDesc), len(file_thawr_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_thawr_v1_control_proto_goTypes,
		DependencyIndexes: file_thawr_v1_control_proto_depIdxs,
		MessageInfos:      file_thawr_v1_control_proto_msgTypes,
	}.Build()
	File_thawr_v1_control_proto = out.File
	file_thawr_v1_control_proto_goTypes = nil
	file_thawr_v1_control_proto_depIdxs = nil
}
